<a href="https://colab.research.google.com/github/Gayatri230/Bangalore-House-Price-Prediction/blob/main/houseprice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df = pd.read_csv('/content/data/House Price.csv', usecols=[1,2,3,4,5,6,7,8,9,12,13])

In [ ]:
df.sample(10)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,yr_built,yr_renovated
3059,420000.0,3,2.00,1200,5029,1.0,0,0,3,1937,1999
4326,370000.0,4,2.75,3150,67518,1.0,0,0,4,1965,0
4106,148226.0,3,1.00,1400,7360,1.0,0,0,4,1968,0
2832,464000.0,3,1.00,1320,3625,2.0,0,0,3,1900,2005
1694,809000.0,4,1.50,1840,4337,2.0,0,0,4,1917,0
3858,600000.0,5,2.00,2190,9072,1.0,0,0,5,1965,0
568,239950.0,3,1.00,1900,33888,1.5,0,0,4,1942,1982
430,583000.0,4,2.50,2660,4000,2.0,0,0,3,2001,0
202,562000.0,5,2.25,3040,8111,2.0,0,0,3,1984,0
2988,565000.0,4,2.75,3260,4900,2.0,0,0,3,2013,1923

In [ ]:
df.shape

(4598, 11)

In [ ]:
df.isnull().sum()

price           0
bedrooms        0
bathrooms       0
sqft_living     0
sqft_lot        0
floors          0
waterfront      0
view            0
condition       0
yr_built        0
yr_renovated    0
dtype: int64

In [ ]:
x = df.iloc[:,1:]
y = df.iloc[:,0]

In [ ]:
x

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,yr_built,yr_renovated
0,3,1.50,1340,7912,1.5,0,0,3,1955,2005
1,5,2.50,3650,9050,2.0,0,4,5,1921,0
2,3,2.00,1930,11947,1.0,0,0,4,1966,0
3,3,2.25,2000,8030,1.0,0,0,4,1963,0
4,4,2.50,1940,10500,1.0,0,0,4,1976,1992
...,...,...,...,...,...,...,...,...,...,...
4593,3,1.75,1510,6360,1.0,0,0,4,1954,1979
4594,3,2.50,1460,7573,2.0,0,0,3,1983,2009
4595,3,2.50,3010,7014,2.0,0,0,3,2009,0
4596,4,2.00,2090,6630,1.0,0,0,3,1974,0
4597,3,2.50,1490,8102,2.0,0,0,4,1990,0

In [ ]:
y

0       3.130000e+05
1       2.384000e+06
2       3.420000e+05
3       4.200000e+05
4       5.500000e+05
            ...
4593    3.081667e+05
4594    5.343333e+05
4595    4.169042e+05
4596    2.034000e+05
4597    2.206000e+05
Name: price, Length: 4598, dtype: float64

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

y = sc.fit_transform(np.array(y).reshape(-1,1))

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)
y_pred = regressor.predict(x_test)
y_pred

array([[-2.16158951e-01],
       [-2.37508121e-01],
       [-7.31756398e-02],
       [ 4.22980885e-01],
       [-4.64546142e-01],
       [ 9.40288928e-02],
       [-1.36905567e-01],
       [-6.75387329e-01],
       [ 6.59415018e-01],
       [-4.27920381e-01],
       [-2.84161719e-01],
       [-6.14619494e-01],
       [ 7.14903169e-01],
       [ 1.26658396e-01],
       [ 8.13834738e-01],
       [-5.41244826e-01],
       [-1.55392133e-01],
       [ 8.61719296e-01],
       [ 5.20743170e-01],
       [-2.81477737e-01],
       [-7.36557966e-01],
       [ 3.32554648e-01],
       [ 7.58096562e-01],
       [ 1.46996050e+00],
       [-6.03617735e-01],
       [ 1.27628796e-01],
       [ 5.62190080e-01],
       [ 1.83642827e+00],
       [-8.05593838e-01],
       [ 2.08813261e-01],
       [ 1.44973508e+00],
       [-3.33323148e-01],
       [-6.65025334e-01],
       [-5.02776056e-01],
       [-7.23060315e-01],
       [-6.24366188e-01],
       [-3.19622081e-01],
       [-4.37584751e-01],
       [ 4.74381010e-01],
       [-6.28689672e-02],
       [-2.03885160e-01],
       [-8.90681187e-01],
       [-2.51910128e-01],
       [-5.42417067e-01],
       [-8.28647215e-01],
       [-1.39848273e-01],
       [ 5.43317919e-01],
       [ 7.45994576e-02],
       [-6.46286720e-01],
       [ 5.08014790e-01],
       [-2.81086625e-01],
       [ 3.76517622e-01],
       [ 2.25018097e+00],
       [ 1.32188450e-01],
       [ 7.45128451e-01],
       [ 4.28145143e-01],
       [-1.09639206e-01],
       [-2.59618071e-01],
       [-3.94594084e-01],
       [ 2.63303420e+00],
       [ 7.29891526e-02],
       [-2.62028275e-02],
       [ 2.50147443e-01],
       [-7.52204949e-01],
       [ 1.04618486e-01],
       [ 1.31047692e+00],
       [ 1.09829831e+00],
       [ 2.30369381e-01],
       [ 2.64810859e-01],
       [-1.01052115e+00],
       [-3.02814988e-01],
       [ 4.77345227e-01],
       [-4.98466448e-01],
       [ 2.57051079e+00],
       [-1.52662265e-01],
       [-7.81328790e-01],
       [-8.60036790e-01],
       [-8.21937707e-01],
       [ 2.07768493e+00],
       [-8.46060185e-01],
       [-4.43816590e-01],
       [-1.10921694e-01],
       [ 1.57860768e-01],
       [-8.57152755e-01],
       [-7.35389857e-01],
       [ 3.23362647e-01],
       [-1.80569020e-01],
       [-1.03913428e+00],
       [-1.63687693e-01],
       [-8.13978467e-01],
       [ 2.84743904e-01],
       [-3.97311478e-01],
       [ 7.98428656e-01],
       [-5.51139546e-01],
       [-5.59770581e-01],
       [ 3.56528600e-01],
       [ 2.06047392e+00],
       [-1.23485931e-01],
       [-5.31347497e-01],
       [ 1.18927219e+00],
       [ 2.06888319e-01],
       [ 7.47089282e-01],
       [-4.24883554e-01],
       [ 1.44086398e+00],
       [-6.95836003e-01],
       [-7.46277598e-01],
       [-3.39917622e-01],
       [-1.61771543e-01],
       [-6.16961817e-01],
       [ 2.41438458e-01],
       [-1.11350326e-01],
       [ 3.63823162e-01],
       [ 8.74387655e-01],
       [ 1.32352933e+00],
       [ 4.41879467e-02],
       [-4.67378271e-01],
       [-7.31648791e-01],
       [ 1.14583532e-01],
       [-5.94337896e-02],
       [-5.16115293e-02],
       [ 7.69118171e-01],
       [-3.34625667e-01],
       [-1.60271483e-01],
       [-1.66576958e-01],
       [ 2.33268616e-01],
       [-6.46361680e-01],
       [-9.58501785e-01],
       [-4.08722487e-01],
       [ 1.29809140e+00],
       [ 1.19137413e-01],
       [-8.26844525e-02],
       [-1.85238204e-01],
       [ 2.06105493e-01],
       [ 5.96794737e-02],
       [ 1.23622752e+00],
       [-3.96103161e-01],
       [ 3.48863775e-01],
       [ 1.35025084e+00],
       [ 1.35890012e+00],
       [-2.16519053e-01],
       [-1.26036581e-01],
       [-3.18552429e-01],
       [ 3.71277865e-01],
       [-3.62270118e-01],
       [-3.50784709e-01],
       [ 1.73973965e+00],
       [ 3.78228187e-01],
       [-4.41650806e-01],
       [-7.19356200e-01],
       [-5.42315213e-01],
       [-3.29513801e-01],
       [-3.03542432e-01],
       [ 1.90062540e+00],
       [-2.52853439e-01],
       [ 2.98544966e-01],
       [-8.51205053e-02],
       [ 7.66491398e-01],
       [-2.53400024e-01],
       [ 1.00169577e+00],
       [-2.37937611e-01],
       [ 6.43628173e-02],
       [ 6.08810103e-01],
       [-1.70786883e-01],
       [-2.34711334e-01],
       [ 5.13571522e-02],
       [-2.31005352e-01],
       [ 4.73881987e-01],
       [-3.94698102e-01],
       [ 2.25605153e-02],
       [-3.58517227e-01],
       [ 1.07056862e-01],
       [-2.50666237e-01],
       [-3.70862430e-01],
       [-2.56987841e-01],
       [ 8.30282264e-01],
       [-5.61272748e-01],
       [ 4.26124708e-01],
       [-5.33262311e-01],
       [-5.14637540e-01],
       [-3.54726984e-01],
       [-3.95969495e-01],
       [ 2.66964459e-01],
       [ 7.16973582e-01],
       [-2.22551519e-01],
       [ 4.99690770e-01],
       [ 3.77374249e-01],
       [ 2.90604713e-01],
       [-5.81236409e-01],
       [ 6.54468984e-01],
       [-5.51465291e-01],
       [-5.12671078e-02],
       [-5.39075374e-01],
       [-2.87341640e-01],
       [-3.80571120e-01],
       [-2.98788509e-01],
       [-8.65159709e-02],
       [-4.12188496e-01],
       [ 4.60987088e-01],
       [-4.24543870e-01],
       [-4.78258887e-01],
       [-2.16440628e-01],
       [ 2.37054108e+00],
       [-4.71894826e-01],
       [-3.15891770e-01],
       [ 3.96053744e-01],
       [-4.18009053e-01],
       [ 2.26429584e-02],
       [ 2.63488827e-01],
       [ 6.48404461e-02],
       [-6.45805248e-02],
       [-3.38187113e-01],
       [-8.99516183e-02],
       [ 4.21077102e-01],
       [ 1.91920671e-01],
       [ 1.05851651e+00],
       [ 1.01501398e+00],
       [ 1.41124818e-03],
       [-5.25626734e-01],
       [ 7.51734746e-01],
       [-1.09032256e-01],
       [-4.75898295e-01],
       [ 2.53215060e-01],
       [-4.17717018e-01],
       [-2.31810053e-01],
       [ 7.15502363e-01],
       [ 1.03118551e+00],
       [-7.88840946e-01],
       [-8.86003978e-01],
       [-8.45512887e-01],
       [ 4.89053195e-01],
       [-6.01736751e-01],
       [ 7.07228772e-01],
       [-4.95952997e-01],
       [-1.34855847e-01],
       [-6.82344591e-01],
       [ 1.03456334e+00],
       [ 2.16951938e-01],
       [-4.31777238e-01],
       [ 8.66830990e-01],
       [-6.27732375e-01],
       [ 3.99369480e-01],
       [-3.92017003e-01],
       [-4.46407149e-01],
       [-3.30499404e-01],
       [-8.72418301e-01],
       [ 6.09061735e-01],
       [ 9.32156035e-01],
       [-2.13390141e-01],
       [ 8.96532563e-01],
       [ 1.74360100e+00],
       [ 4.88071091e-01],
       [-8.16338246e-02],
       [ 7.82648873e-01],
       [ 2.91195334e-02],
       [ 5.62263700e-01],
       [-2.47776239e-01],
       [ 5.77999826e-01],
       [-7.10416589e-02],
       [ 9.10346726e-01],
       [ 9.35617227e-01],
       [-7.07993684e-01],
       [-6.53266163e-01],
       [ 8.92290130e-02],
       [-8.65720252e-02],
       [-6.57367406e-01],
       [ 3.13509014e-01],
       [-8.25488206e-01],
       [-8.69340090e-01],
       [ 2.31375121e-01],
       [ 2.81712642e-01],
       [-5.81903059e-01],
       [-6.49044286e-01],
       [ 1.30277649e-01],
       [-1.05045129e-01],
       [-1.17746564e-01],
       [-5.14006193e-01],
       [-5.11697522e-01],
       [-5.68815868e-01],
       [-9.31028961e-01],
       [ 2.86183047e-01],
       [-8.64170466e-01],
       [-4.84698625e-02],
       [ 3.15529748e-01],
       [-7.06232303e-01],
       [ 7.57830334e-01],
       [-5.78497310e-02],
       [ 2.47246640e-01],
       [ 3.21222016e-01],
       [-1.19540483e-01],
       [-8.26161220e-01],
       [-3.74345174e-01],
       [-9.07494461e-02],
       [-3.74601265e-01],
       [-2.63992126e-01],
       [-3.16029095e-01],
       [-4.85605531e-01],
       [-6.87969839e-01],
       [-7.22843056e-02],
       [-9.04710002e-01],
       [-1.79281870e-01],
       [-7.49096644e-01],
       [ 6.98672254e-01],
       [ 1.93671073e-01],
       [ 1.31439769e-01],
       [-7.67909931e-01],
       [ 4.10888781e-01],
       [-7.09146316e-01],
       [ 1.66888938e-01],
       [-5.31262350e-01],
       [ 1.01976595e+00],
       [-4.38042636e-01],
       [-2.61359386e-01],
       [ 3.16048090e-01],
       [ 2.39500319e-01],
       [-5.31125869e-01],
       [-6.36569122e-01],
       [-2.25421800e-01],
       [ 1.12546784e+00],
       [ 8.20969228e-01],
       [ 8.79391149e-01],
       [ 2.18597741e-02],
       [ 1.30823927e+00],
       [-7.00528415e-01],
       [ 1.63341086e+00],
       [ 5.61072271e-02],
       [ 5.07586904e-01],
       [ 1.39946409e-01],
       [ 2.27493957e-01],
       [ 1.52625384e-01],
       [-9.53241498e-01],
       [-3.48386782e-01],
       [ 3.14484290e-01],
       [-3.47573049e-01],
       [-7.55996172e-01],
       [ 6.24398422e-02],
       [ 8.76044802e-01],
       [ 1.36586686e+00],
       [ 5.13359100e-01],
       [-3.04436054e-01],
       [-1.99072466e-02],
       [-3.31473847e-01],
       [-3.94355880e-01],
       [ 1.35979945e+00],
       [ 1.55301545e-01],
       [-9.72718214e-01],
       [-3.91580618e-01],
       [ 7.14206272e-02],
       [-8.88791705e-01],
       [ 1.31163907e-01],
       [-7.75148021e-01],
       [-3.28706663e-01],
       [ 7.66476191e-02],
       [-3.80143838e-01],
       [-6.61337275e-01],
       [-9.15767601e-01],
       [-7.05042534e-01],
       [-2.54330175e-01],
       [-8.59010928e-01],
       [ 6.14534721e-01],
       [ 1.12495389e+00],
       [-5.12927242e-02],
       [-7.90764379e-01],
       [-5.51480798e-01],
       [-5.16031705e-02],
       [ 5.65067275e-03],
       [-6.19116993e-01],
       [-1.91457314e-01],
       [-6.87206051e-01],
       [ 3.93027873e-01],
       [-1.59652131e-01],
       [-4.68313341e-01],
       [-6.62983321e-01],
       [ 1.02563109e+00],
       [-9.63694030e-01],
       [-3.62018418e-02],
       [-8.01831256e-01],
       [ 2.83743639e-01],
       [ 2.60493376e-01],
       [-8.05437188e-01],
       [ 2.39446888e-01],
       [ 3.32114861e-01],
       [-1.36997151e-01],
       [ 2.22040950e-01],
       [-2.13717300e-01],
       [-9.00312768e-01],
       [ 2.75898900e-01],
       [-3.78143924e-01],
       [-1.70523437e-01],
       [-3.26045183e-01],
       [-4.92490155e-01],
       [-8.57517350e-01],
       [ 5.63452996e-01],
       [ 2.07722653e-01],
       [-4.09080702e-01],
       [-4.56391990e-01],
       [-7.59068239e-01],
       [ 1.08046009e+00],
       [-4.31862017e-01],
       [ 8.16344508e-01],
       [-2.02707457e-01],
       [ 3.03494206e-03],
       [-5.68604405e-01],
       [-7.86161628e-01],
       [ 1.34618361e+00],
       [ 1.00672227e+00],
       [-2.68910826e-01],
       [-1.33233167e-01],
       [-1.09475069e-02],
       [ 8.37736481e-01],
       [-2.14212544e-01],
       [-2.46597263e-01],
       [-4.79779556e-01],
       [ 2.85519784e-01],
       [ 1.88794090e-01],
       [-2.63233360e-01],
       [ 3.29257070e-01],
       [-3.98605415e-01],
       [-1.44119004e-02],
       [-4.07620047e-01],
       [ 4.48285378e-01],
       [-1.61856043e-01],
       [ 2.93376347e-01],
       [-2.43249786e-02],
       [ 1.25260736e-01],
       [-3.88780981e-01],
       [-2.05680713e-01],
       [-8.23536378e-01],
       [-3.06326485e-01],
       [-1.06378045e-01],
       [-5.14208947e-01],
       [-6.23271767e-01],
       [-4.05312040e-01],
       [-3.03692383e-01],
       [ 4.45130241e-02],
       [ 1.17146607e+00],
       [ 1.24271750e-01],
       [ 5.12422006e-01],
       [ 9.83224619e-01],
       [ 3.21008931e+00],
       [ 2.49003662e-01],
       [ 4.05471572e-01],
       [-3.88243520e-01],
       [-5.15001559e-01],
       [-7.84077304e-01],
       [-3.38035437e-01],
       [-7.05968826e-01],
       [ 1.27808113e-01],
       [-3.38401314e-01],
       [ 1.09671121e+00],
       [ 8.20879133e-01],
       [-2.51526902e-02],
       [-5.44659003e-01],
       [-2.04404744e-02],
       [-1.27417613e-01],
       [ 1.69947641e-02],
       [ 1.72012711e+00],
       [-4.38858130e-01],
       [ 1.36978819e+00],
       [ 9.31626471e-01],
       [-5.67104160e-01],
       [-6.33537348e-01],
       [-2.92137083e-01],
       [ 9.04601068e-01],
       [-1.50572687e-01],
       [-1.53582024e-02],
       [ 3.94568454e-01],
       [ 3.47863183e-01],
       [-1.92023877e-01],
       [-2.36387042e-01],
       [ 2.81588097e-01],
       [ 1.96159983e-01],
       [ 9.96420794e-01],
       [ 2.40635467e-01],
       [ 1.13106590e+00],
       [ 3.56016724e-01],
       [-6.73014209e-02],
       [ 7.79103497e-02],
       [ 2.36812207e+00],
       [-8.84378291e-01],
       [-7.66314837e-01],
       [ 1.47592443e+00],
       [ 5.54281252e-01],
       [-6.68287657e-01],
       [-5.46058709e-01],
       [ 2.35892823e-01],
       [-1.93595183e-01],
       [-3.95329486e-01],
       [-8.05217837e-01],
       [ 6.56831976e-01],
       [ 4.01062545e-01],
       [ 3.68737969e-01],
       [ 2.75192176e-01],
       [-5.41701618e-01],
       [-3.67418032e-01],
       [ 1.85934520e+00],
       [-4.75354555e-01],
       [-4.15366385e-01],
       [-5.11392393e-01],
       [ 2.11465137e-02],
       [-2.57287680e-01],
       [-7.84201956e-01],
       [-7.86934435e-02],
       [ 6.55262602e-01],
       [-4.39694517e-01],
       [-5.94787697e-02],
       [ 1.09488012e-01],
       [ 4.48935725e-01],
       [ 3.73857765e-01],
       [ 2.66926845e-01],
       [-4.10378346e-01],
       [ 3.56115208e+00],
       [-9.24283086e-01],
       [ 1.87119660e-01],
       [-7.32207368e-01],
       [ 7.47235404e-01],
       [-7.60875723e-01],
       [-1.55385439e-01],
       [-1.00781410e-01],
       [ 8.54186611e-02],
       [ 3.55846375e-01],
       [-8.43586485e-01],
       [ 4.35594833e-02],
       [-3.19808337e-01],
       [ 1.70958257e+00],
       [-2.09409494e-01],
       [ 8.30109446e-01],
       [-2.63061515e-01],
       [-4.47310753e-02],
       [ 3.43678379e-01],
       [ 1.42780923e+00],
       [-1.46938001e-01],
       [ 7.05539481e-01],
       [-3.71319793e-01],
       [-1.20376736e-01],
       [-6.68729469e-01],
       [ 3.72789865e-02],
       [-2.37820858e-01],
       [-5.68538178e-01],
       [ 9.92149856e-02],
       [-2.25506739e-02],
       [ 1.22795212e+00],
       [ 2.71473620e+00],
       [ 5.48375306e-01],
       [ 9.65476970e-01],
       [-3.55283486e-02],
       [-7.39482669e-01],
       [-8.86407261e-01],
       [ 1.44043771e+00],
       [-4.71573461e-01],
       [ 7.44578083e-01],
       [-3.07239278e-01],
       [ 1.63830865e+00],
       [-2.39531689e-01],
       [ 6.64925738e-02],
       [-6.17611838e-01],
       [-5.08456426e-01],
       [ 6.41889383e-02],
       [ 3.13576256e-01],
       [-2.47639875e-02],
       [-5.59491710e-02],
       [-4.29623161e-01],
       [-2.17852448e-01],
       [-3.38775250e-01],
       [-1.59224288e-01],
       [ 1.01377037e+00],
       [ 5.38510736e-02],
       [-9.94890193e-01],
       [ 1.83661277e-01],
       [ 9.80487715e-02],
       [ 1.81362751e-02],
       [-6.29666337e-01],
       [ 1.07405092e-01],
       [ 1.18791782e-01],
       [-7.79129877e-01],
       [-2.57313817e-01],
       [-5.67692497e-02],
       [ 3.29877172e-01],
       [-6.43756553e-01],
       [-3.33823646e-01],
       [-3.10657026e-01],
       [-5.60776707e-01],
       [-7.70863984e-01],
       [ 5.76914092e-01],
       [-3.46141443e-01],
       [ 1.26707395e-01],
       [-6.55375441e-02],
       [ 1.53079554e-01],
       [ 7.14427846e-01],
       [-1.75343499e-01],
       [-2.97138037e-01],
       [ 8.67863226e-02],
       [ 4.00210882e-01],
       [-6.33431030e-01],
       [-8.38723289e-01],
       [-8.36868376e-01],
       [-7.25101156e-02],
       [-9.09304034e-01],
       [-6.65274544e-01],
       [-6.17776564e-01],
       [ 9.32929637e-01],
       [ 4.13496592e-01],
       [-6.90009884e-01],
       [ 1.65672416e-02],
       [-5.92998919e-01],
       [-3.83837287e-01],
       [-5.77654273e-02],
       [ 6.09497982e-01],
       [-1.25475825e-01],
       [-8.21201175e-02],
       [-3.08234220e-01],
       [ 9.01584468e-01],
       [-4.42536127e-01],
       [ 2.97075488e-01],
       [ 1.69192532e+00],
       [-6.19016208e-01],
       [-5.99461381e-01],
       [ 5.63804657e-01],
       [ 1.41167385e+00],
       [-2.39828287e-01],
       [-6.32230440e-02],
       [-4.79190857e-01],
       [-1.48002910e-01],
       [ 3.04847737e-01],
       [ 1.43459421e-01],
       [-1.00319845e+00],
       [-4.42636077e-01],
       [-8.25594044e-01],
       [ 1.88203221e+00],
       [ 3.72231175e-02],
       [-4.74632297e-01],
       [-6.77519977e-01],
       [-5.35777867e-01],
       [ 5.01288161e-01],
       [ 2.12231098e-01],
       [ 1.90278523e+00],
       [ 9.89424426e-01],
       [-3.53605112e-01],
       [-4.85859815e-01],
       [ 4.42860770e-01],
       [ 7.80204597e-02],
       [ 1.92888074e-01],
       [ 1.19523749e+00],
       [-1.76450891e-01],
       [-2.88794015e-03],
       [-6.62387887e-03],
       [-5.04419835e-01],
       [ 4.13325319e-01],
       [-2.19001547e-01],
       [-7.79536024e-01],
       [ 2.68796733e-01],
       [ 1.45575127e+00],
       [ 3.66242140e-01],
       [-3.56801425e-01],
       [-1.08707580e-01],
       [ 4.37142396e-01],
       [-3.62884920e-01],
       [-7.46398183e-01],
       [ 7.77394771e-01],
       [-1.60852814e-01],
       [ 7.93487610e-02],
       [-1.15247226e-02],
       [ 4.96884703e-01],
       [-4.30345869e-01],
       [ 1.78171025e+00],
       [-3.85569459e-01],
       [-4.23914821e-01],
       [ 3.00465230e-01],
       [ 2.48375341e-01],
       [-3.55142140e-01],
       [ 1.20778452e+00],
       [ 1.35762613e+00],
       [-7.77495296e-02],
       [ 1.49340064e+00],
       [ 1.02231119e+00],
       [ 3.57752514e-02],
       [-1.73602153e-01],
       [-3.09282392e-01],
       [-4.95455398e-01],
       [ 9.64624201e-01],
       [ 2.34951381e+00],
       [ 8.00390694e-02],
       [-1.40225524e-01],
       [ 4.28365713e-01],
       [-4.39854904e-01],
       [ 2.40624267e+00],
       [-7.99757558e-01],
       [-6.37463544e-01],
       [ 5.22893468e-01],
       [-2.24746409e-01],
       [-2.03747378e-01],
       [-2.18048007e-01],
       [ 2.53103303e+00],
       [ 6.26656516e-02],
       [-2.95003194e-01],
       [-2.96912282e-01],
       [-5.08851752e-01],
       [ 6.58667088e-01],
       [-8.06397835e-01],
       [-2.38734511e-02],
       [-5.41855238e-01],
       [-7.74108308e-01],
       [-7.35986455e-01],
       [-6.42312647e-02],
       [-2.90292449e-01],
       [ 3.44583957e+00],
       [ 7.23242569e-01],
       [-2.65802403e-01],
       [-1.40724533e-01],
       [-4.90916344e-01],
       [-6.71352008e-01],
       [ 2.76890222e-03],
       [ 3.66431301e-01],
       [ 9.78333720e-01],
       [ 4.44710568e-01],
       [ 7.28583004e-01],
       [-3.57824865e-01],
       [ 2.56769665e-01],
       [-1.60808412e-01],
       [ 2.48236361e-01],
       [-1.58557452e-01],
       [ 1.78840073e+00],
       [ 5.39946847e-01],
       [-2.08923079e-01],
       [ 3.40043315e-01],
       [-7.15762367e-01],
       [-2.73359556e-01],
       [-2.22215304e-01],
       [-6.99478257e-04],
       [-9.85086497e-02],
       [-1.02465265e-01],
       [-3.05709632e-01],
       [-1.09673048e-01],
       [ 7.39181846e-01],
       [-2.91950652e-01],
       [ 1.81448176e-01],
       [-3.63809225e-01],
       [-3.24014588e-01],
       [-1.76315822e-01],
       [-3.31138977e-01],
       [ 1.06281975e+00],
       [ 8.06002932e-01],
       [-2.61558703e-01],
       [-1.67603018e-01],
       [-1.91457606e-03],
       [ 3.61297606e+00],
       [ 6.92863712e-01],
       [-3.66030872e-01],
       [-3.38639234e-01],
       [-4.21463617e-01],
       [-5.11185009e-01],
       [ 1.20700809e+00],
       [-1.22099341e-01],
       [ 5.19885113e-02],
       [-8.48308537e-01],
       [-5.73516864e-01],
       [-4.20689764e-01],
       [-1.50204350e-01],
       [ 1.12722282e-01],
       [ 3.70669474e-01],
       [-7.58954004e-01],
       [ 8.90189793e-01],
       [ 1.07839882e-01],
       [-2.17773196e-01],
       [-1.18396311e+00],
       [ 4.12422700e-01],
       [ 3.91283731e-01],
       [ 3.01579837e-01],
       [ 7.48660825e-02],
       [-6.69731338e-01],

In [ ]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train, y_train)
print(model.score(x_test, y_test))

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.4740502960405828

In [ ]:
model.score(x,y)

0.8439919022362685

In [ ]:
x_test

array([[-0.44123687,  1.38958741, -0.52900815, ..., -0.66701597,
         1.21802499, -0.82562297],
       [ 1.75920471, -0.52405196,  0.19773042, ...,  0.80960388,
        -0.09366497, -0.82562297],
       [ 0.65898392,  0.11382783, -0.03067313, ...,  0.80960388,
         0.27629886, -0.82562297],
       ...,
       [-0.44123687, -1.48087164, -1.31803859, ..., -0.66701597,
        -0.0600319 ,  1.23096784],
       [-1.54145766, -1.48087164, -1.39071245, ...,  0.80960388,
        -0.90085879, -0.82562297],
       [ 0.65898392,  0.43276772,  0.10429261, ..., -0.66701597,
         0.41083117,  1.22586211]])

In [ ]:
y_test

array([[-4.28059751e-01],
       [-5.22515587e-01],
       [ 5.77131158e-02],
       [ 5.54280935e-01],
       [-2.52641771e-01],
       [-5.22515587e-01],
       [-3.61940667e-01],
       [-4.88781360e-01],
       [ 1.90634875e+00],
       [-1.04211173e-01],
       [ 6.10954437e-01],
       [-5.56338865e-02],
       [-2.93122844e-01],
       [ 1.11687879e-01],
       [ 8.53840870e-01],
       [-9.27326309e-01],
       [-1.47930731e-01],
       [ 6.89757591e-01],
       [ 3.47827467e-01],
       [ 1.92650023e-01],
       [-5.87015428e-01],
       [ 5.40787245e-01],
       [-1.46707394e+00],
       [ 1.70394339e+00],
       [-8.05883092e-01],
       [ 9.61790396e-01],
       [ 5.83832118e-01],
       [ 1.55551279e+00],
       [-8.59857855e-01],
       [-3.36302654e-01],
       [ 1.86473960e+00],
       [-8.03184354e-01],
       [-2.79629153e-01],
       [ 1.92650023e-01],
       [-7.65402020e-01],
       [-5.25214325e-01],
       [-7.76331910e-01],
       [-5.15768741e-01],
       [ 5.59678412e-01],
       [-6.57452494e-01],
       [-3.60591297e-01],
       [-1.06361259e+00],
       [-7.51908329e-01],
       [-2.79629153e-01],
       [-7.23571579e-01],
       [-2.66135462e-01],
       [ 4.22042766e-01],
       [-3.87862047e-01],
       [-5.44105492e-01],
       [-5.02364102e-02],
       [-5.36009277e-01],
       [-3.39001392e-01],
       [-1.46707394e+00],
       [ 1.56900648e+00],
       [ 6.91916581e-01],
       [ 2.89480748e-01],
       [-7.24920948e-01],
       [-7.78895711e-01],
       [-6.33163851e-01],
       [ 5.29992292e-01],
       [-4.77986407e-01],
       [ 1.72320435e-02],
       [ 3.65369265e-01],
       [-5.36009277e-01],
       [ 5.16498601e-01],
       [ 7.27000177e-01],
       [ 2.75645127e+00],
       [ 9.81941880e-02],
       [-5.02364102e-02],
       [-5.11720634e-01],
       [ 1.72320435e-02],
       [ 4.89511220e-01],
       [-7.83213692e-01],
       [ 1.96032351e+00],
       [ 5.27293554e-01],
       [-8.35569212e-01],
       [-7.78895711e-01],
       [-9.73731112e-01],
       [ 2.02954075e+00],
       [-7.44351862e-01],
       [-2.12160699e-01],
       [-1.50089722e-01],
       [ 1.73758856e-01],
       [-1.03527584e+00],
       [-8.35569212e-01],
       [-9.11133880e-01],
       [-4.29678994e-01],
       [-1.09194934e+00],
       [-6.70946185e-01],
       [-5.26347795e-01],
       [ 5.24594816e-01],
       [-8.97640189e-01],
       [ 5.14339611e-01],
       [-9.67807381e-01],
       [-2.66135462e-01],
       [ 3.00599549e-01],
       [ 7.86372416e-01],
       [-5.31961170e-01],
       [-1.85173318e-01],
       [ 1.00092210e+00],
       [-1.71679627e-01],
       [-3.78133095e-01],
       [-3.60591297e-01],
       [ 6.91916581e-01],
       [-3.93003143e-01],
       [-6.34513220e-01],
       [-6.16971422e-01],
       [ 2.76310906e-01],
       [ 4.67921315e-01],
       [ 4.08549075e-01],
       [-3.33603916e-01],
       [-4.03771108e-01],
       [-1.78515524e-02],
       [-9.75533796e-03],
       [-2.52641771e-01],
       [-1.44692245e-01],
       [-2.66135462e-01],
       [-6.42622928e-01],
       [-2.58039248e-01],
       [-6.57452494e-01],
       [-1.85173318e-01],
       [ 2.04794345e-01],
       [ 4.98867752e-02],
       [ 2.47164534e-01],
       [ 1.11157036e+00],
       [-5.37358646e-01],
       [-4.95663142e-01],
       [-6.39999748e-02],
       [ 5.16363664e-01],
       [ 5.97460746e-01],
       [-5.76760223e-01],
       [-5.76490350e-01],
       [-2.39714816e-01],
       [ 1.52168951e-01],
       [ 7.70045051e-01],
       [ 7.18903963e-01],
       [-3.14712749e-01],
       [ 1.07378803e+00],
       [ 1.40708219e+00],
       [ 2.60118477e-01],
       [-2.25654390e-01],
       [-5.33310539e-01],
       [ 2.27733619e-01],
       [-7.49209591e-01],
       [-4.44252180e-01],
       [-1.46707394e+00],
       [-1.46707394e+00],
       [-9.54313691e-01],
       [-7.65402020e-01],
       [-3.74084988e-01],
       [-2.93122844e-01],
       [ 3.34244724e-02],
       [ 1.98731089e+00],
       [-6.97933566e-01],
       [ 5.00392532e-01],
       [ 4.51728886e-01],
       [ 3.32984407e-01],
       [-4.84760240e-01],
       [ 3.19634558e+00],
       [ 3.68068003e-01],
       [-4.14566061e-01],
       [-3.62955392e-01],
       [ 1.76457594e-01],
       [-3.87713616e-01],
       [ 7.45891344e-01],
       [-2.79629153e-01],
       [-3.90277417e-01],
       [-9.09873563e-02],
       [ 3.14093240e-01],
       [-3.09315273e-01],
       [-5.62996659e-01],
       [-6.83748999e-01],
       [-7.82943818e-01],
       [-5.76490350e-01],
       [ 1.97381720e+00],
       [-7.31756845e-02],
       [ 9.61790396e-01],
       [-7.79975206e-01],
       [-2.66553767e-01],
       [-4.63143347e-01],
       [-1.03527584e+00],
       [ 8.47004973e-02],
       [ 1.11022099e+00],
       [ 4.42194250e-02],
       [ 2.22336143e-01],
       [-5.09021896e-01],
       [-1.85173318e-01],
       [-4.14566061e-01],
       [-4.28059751e-01],
       [ 3.54574312e-01],
       [-2.66135462e-01],
       [-5.22515587e-01],
       [-2.05502906e-02],
       [-1.15006126e-01],
       [-5.36009277e-01],
       [ 1.36660112e+00],
       [-2.39148081e-01],
       [ 1.65662642e-01],
       [-2.45983978e-02],
       [-7.41113377e-01],
       [-1.31198555e-01],
       [ 1.02925885e+00],
       [-5.55046851e-01],
       [-7.26270317e-01],
       [ 1.23166421e+00],
       [ 2.37179203e-01],
       [-1.85173318e-01],
       [ 1.79156333e-01],
       [ 3.53494817e-01],
       [-2.32490287e-02],
       [-7.88191364e-01],
       [-3.95674893e-01],
       [ 7.86372416e-01],
       [-3.67427195e-02],
       [ 2.79693234e+00],
       [ 7.99866107e-01],
       [-2.47244295e-01],
       [-7.54607067e-01],
       [-2.39148081e-01],
       [ 6.24448127e-01],
       [-3.60591297e-01],
       [ 4.89511220e-01],
       [-5.96730886e-01],
       [-4.95528205e-01],
       [ 4.54427624e-01],
       [ 7.56686297e-01],
       [-7.92524338e-01],
       [-7.92389402e-01],
       [-8.05883092e-01],
       [ 6.89217843e-01],
       [-6.97933566e-01],
       [-6.37301010e-02],
       [-6.37301010e-02],
       [ 3.34244724e-02],
       [-6.25067636e-01],
       [ 6.71676045e-01],
       [-1.46707394e+00],
       [ 1.52168951e-01],
       [ 1.50153803e+00],
       [-1.64932782e-01],
       [-5.60297921e-01],
       [-5.02364102e-02],
       [-6.03477731e-01],
       [-2.53991141e-01],
       [-6.16971422e-01],
       [ 8.60587716e-01],
       [ 4.11247813e-01],
       [-3.67427195e-02],
       [ 8.33870208e-01],
       [ 1.12371469e+00],
       [ 7.99866107e-01],
       [-2.12160699e-01],
       [ 3.14093240e-01],
       [-5.22515587e-01],
       [ 1.32311905e+00],
       [ 9.12786715e-02],
       [ 2.87105859e-01],
       [ 3.07257343e-02],
       [ 1.01576516e+00],
       [ 1.15070207e+00],
       [-9.11133880e-01],
       [-7.81594449e-01],
       [ 6.88678095e-01],
       [-6.11573945e-01],
       [-4.59095240e-01],
       [ 7.45621470e-01],
       [-5.76490350e-01],
       [-2.51600830e-01],
       [-4.68540824e-01],
       [-4.14566061e-01],
       [-5.38708015e-01],
       [-1.98667008e-01],
       [-3.94325524e-01],
       [-2.93122844e-01],
       [ 1.87252547e-01],
       [-3.31309989e-01],
       [-7.65402020e-01],
       [-7.72237917e-02],
       [-5.22650523e-01],
       [ 7.05410272e-01],
       [-8.86845237e-01],
       [-3.39438588e-01],
       [ 3.27586931e-01],
       [-5.60432858e-01],
       [ 1.04275254e+00],
       [ 1.11687879e-01],
       [ 2.73612168e-01],
       [ 6.97314057e-01],
       [-3.71217579e-01],
       [-1.17471064e+00],
       [-1.58185936e-01],
       [ 1.11687879e-01],
       [-8.73351546e-01],
       [-9.07174825e-02],
       [ 1.52168951e-01],
       [-8.32870474e-01],
       [-6.11406961e-01],
       [-5.36009277e-01],
       [-5.57599182e-01],
       [-8.05883092e-01],
       [-5.68696394e-01],
       [ 3.14093240e-01],
       [-1.04211173e-01],
       [ 3.95055385e-01],
       [-1.10184471e+00],
       [ 8.26853489e-01],
       [-8.46364165e-01],
       [ 4.03151599e-01],
       [-4.79335776e-01],
       [ 1.25865159e+00],
       [-5.09021896e-01],
       [-3.74084988e-01],
       [ 1.06973992e+00],
       [ 5.83967055e-01],
       [-8.24909196e-01],
       [-9.13967555e-01],
       [-3.06616534e-01],
       [ 4.89511220e-01],
       [-1.46707394e+00],
       [ 8.94321942e-01],
       [-3.57892559e-01],
       [-2.22955652e-01],
       [-5.43025996e-01],
       [ 2.33131096e-01],
       [-1.44692245e-01],
       [-4.45601549e-01],
       [-7.11427257e-01],
       [ 7.75577464e-01],
       [ 1.49470213e-01],
       [-6.70946185e-01],
       [ 7.12068065e-02],
       [ 5.46184721e-01],
       [-5.92682778e-01],
       [-2.39148081e-01],
       [-8.32937942e-01],
       [ 8.94321942e-01],
       [ 9.34803015e-01],
       [ 3.81561694e-01],
       [-6.41260065e-01],
       [-2.79629153e-01],
       [ 3.54574312e-01],
       [-7.24920948e-01],
       [ 9.61790396e-01],
       [ 5.70338427e-01],
       [-8.73621420e-01],
       [-5.79189088e-01],
       [ 2.33131096e-01],
       [-4.55047133e-01],
       [-5.49529955e-01],
       [-1.04876953e+00],
       [-2.79629153e-01],
       [ 1.69044970e+00],
       [-6.43958803e-01],
       [-3.87578679e-01],
       [-8.65255332e-01],
       [-9.19230095e-01],
       [-7.72237917e-02],
       [-5.22515587e-01],
       [ 7.72878726e-01],
       [ 1.36660112e+00],
       [ 9.34803015e-01],
       [-5.76625286e-01],
       [-3.51145714e-01],
       [ 3.95055385e-01],
       [ 4.15206869e-02],
       [-1.03068798e+00],
       [-3.39001392e-01],
       [-4.82034514e-01],
       [ 9.85585177e-02],
       [ 2.84407120e-01],
       [-9.07174825e-02],
       [-6.38561327e-01],
       [-2.81428312e-01],
       [-6.03477731e-01],
       [ 1.32612005e+00],
       [-1.20403602e-01],
       [ 7.05396778e-01],
       [-7.92389402e-01],
       [-3.06616534e-01],
       [ 3.59971789e-01],
       [ 3.35092796e-01],
       [-1.24540761e-02],
       [-6.64288391e-02],
       [-9.67807381e-01],
       [-6.48006911e-01],
       [-4.41553442e-01],
       [-1.58185936e-01],
       [-6.78271331e-01],
       [-7.78895711e-01],
       [-1.46707394e+00],
       [-4.02489207e-01],
       [ 2.46624786e-01],
       [-1.95965572e-01],
       [-3.65988774e-01],
       [-4.28059751e-01],
       [-1.13043334e+00],
       [ 3.59306009e+00],
       [-8.05883092e-01],
       [ 1.02925885e+00],
       [-2.79629153e-01],
       [ 1.03591664e-01],
       [ 2.06143714e-01],
       [-1.14120131e+00],
       [ 1.23166421e+00],
       [-1.71679627e-01],
       [-3.33603916e-01],
       [ 1.68361380e-01],
       [-2.43196188e-01],
       [ 2.10875411e+00],
       [-5.36009277e-01],
       [-5.67071753e-01],
       [ 1.52168951e-01],
       [ 5.77131158e-02],
       [ 4.69181632e-02],
       [-5.61647290e-01],
       [ 3.14093240e-01],
       [-6.22368898e-01],
       [-1.44692245e-01],
       [ 1.19784093e-01],
       [ 8.26853489e-01],
       [-4.17264799e-01],
       [ 3.46478098e-01],
       [ 8.47004973e-02],
       [-1.46707394e+00],
       [-7.33017162e-01],
       [-7.78895711e-01],
       [-9.13832618e-01],
       [ 9.81941880e-02],
       [ 8.94321942e-01],
       [-2.79224342e-01],
       [-7.92389402e-01],
       [-8.86845237e-01],
       [-6.57452494e-01],
       [-2.52641771e-01],
       [ 2.04128566e+00],
       [-4.82034514e-01],
       [ 1.74442446e+00],
       [ 5.27293554e-01],
       [ 1.21817052e+00],
       [-3.17411487e-01],
       [ 1.17499071e+00],
       [-5.09021896e-01],
       [-5.62996659e-01],
       [-8.47713534e-01],
       [-8.05883092e-01],
       [-3.20110225e-01],
       [ 1.69621697e-02],
       [-4.16590114e-01],
       [ 7.59385035e-01],
       [ 1.76601436e+00],
       [-3.87880938e-01],
       [ 7.72878726e-01],
       [-1.04211173e-01],
       [-6.87138614e-01],
       [ 1.52168951e-01],
       [ 3.57956640e+00],
       [-7.11427257e-01],
       [ 4.13280772e+00],
       [ 6.59531723e-01],
       [ 5.77131158e-02],
       [ 1.72320435e-02],
       [-2.31051866e-01],
       [ 1.09672730e+00],
       [-9.75533796e-03],
       [ 5.77131158e-02],
       [ 4.69181632e-02],
       [ 3.54574312e-01],
       [ 1.11687879e-01],
       [-5.29351484e-02],
       [ 4.89511220e-01],
       [-1.17839801e-01],
       [ 6.51435509e-01],
       [-3.63559909e-01],
       [ 6.48736771e-01],
       [ 6.63579831e-01],
       [ 8.73992354e-02],
       [-6.43958803e-01],
       [ 2.19491133e+00],
       [-6.03477731e-01],
       [-9.00338928e-01],
       [-3.67427195e-02],
       [ 5.83967055e-01],
       [-5.02364102e-02],
       [-5.87285302e-01],
       [ 4.49030148e-01],
       [ 4.96169013e-02],
       [-3.67427195e-02],
       [-9.81301072e-01],
       [ 1.36660112e+00],
       [ 2.06143714e-01],
       [ 3.07346395e-01],
       [ 2.93852704e-01],
       [-8.70652808e-01],
       [-8.59857855e-01],
       [ 2.04128566e+00],
       [-3.60591297e-01],
       [-5.22515587e-01],
       [-3.40350761e-01],
       [-3.47097607e-01],
       [-3.13452432e-02],
       [-4.17264799e-01],
       [ 1.52168951e-01],
       [ 1.16419576e+00],
       [-4.26710382e-01],
       [-5.02364102e-02],
       [ 2.73612168e-01],
       [ 3.38381883e-01],
       [ 8.33600334e-01],
       [ 6.27011929e-01],
       [ 1.65662642e-01],
       [ 7.16888814e+00],
       [-9.40820000e-01],
       [-2.79629153e-01],
       [-6.97933566e-01],
       [ 1.90634875e+00],
       [-6.43958803e-01],
       [ 3.73835279e-03],
       [ 2.19637405e-01],
       [ 1.52034014e-01],
       [ 2.73612168e-01],
       [-4.28059751e-01],
       [-2.28353128e-01],
       [ 2.22336143e-01],
       [ 1.83213345e+00],
       [ 3.07257343e-02],
       [ 1.12371469e+00],
       [ 1.03961464e-03],
       [-5.76760223e-01],
       [-3.74084988e-01],
       [ 1.36660112e+00],
       [-3.87578679e-01],
       [ 2.33814685e+00],
       [-6.35412799e-01],
       [ 1.41071740e-01],
       [-6.41260065e-01],
       [-2.52641771e-01],
       [ 3.60240489e-01],
       [-1.74378365e-01],
       [ 7.18769026e-01],
       [-6.33298788e-01],
       [ 2.94806167e+00],
       [ 1.59599386e+00],
       [ 1.96032351e+00],
       [ 8.29552227e-01],
       [-7.38414639e-01],
       [-8.32870474e-01],
       [-6.30465113e-01],
       [ 1.55551279e+00],
       [-8.46364165e-01],
       [ 1.18308692e+00],
       [-2.29260204e-01],
       [ 3.39065473e+00],
       [-3.60591297e-01],
       [-3.12354052e-01],
       [-8.38267950e-01],
       [-2.08112592e-01],
       [ 8.47004973e-02],
       [-5.22785460e-01],
       [ 2.87105859e-01],
       [ 3.68068003e-01],
       [ 2.26295198e-02],
       [-5.93132568e-01],
       [-6.11573945e-01],
       [-1.98667008e-01],
       [ 1.52166252e-01],
       [ 1.11687879e-01],
       [-7.14395869e-01],
       [-5.36144214e-01],
       [-6.91186721e-01],
       [ 1.99307817e-02],
       [-1.46707394e+00],
       [-1.85173318e-01],
       [-7.45250536e-02],
       [-6.03477731e-01],
       [-2.52641771e-01],
       [ 9.61790396e-01],
       [-6.30465113e-01],
       [-9.75533796e-03],
       [-6.96584197e-01],
       [-5.49637905e-01],
       [-4.65842085e-01],
       [-7.19523471e-01],
       [ 7.18769026e-01],
       [-8.00485616e-01],
       [-2.52641771e-01],
       [-6.70946185e-01],
       [ 2.19637405e-01],
       [ 1.52168951e-01],
       [-8.39339349e-01],
       [-3.87578679e-01],
       [-1.85173318e-01],
       [ 4.08549075e-01],
       [-6.46657541e-01],
       [-1.14322536e+00],
       [-1.19720012e+00],
       [-1.58185936e-01],
       [-9.00338928e-01],
       [-8.59857855e-01],
       [-4.75376721e-02],
       [ 8.94321942e-01],
       [-6.03477731e-01],
       [-6.03477731e-01],
       [-2.79629153e-01],
       [ 1.08989141e-01],
       [ 1.72320435e-02],
       [-7.40607363e-01],
       [ 3.07257343e-02],
       [-1.25801078e-01],
       [-3.97923842e-01],
       [-1.74378365e-01],
       [ 2.17622256e+00],
       [-4.82034514e-01],
       [ 1.65662642e-01],
       [ 1.36390238e+00],
       [-8.19376783e-01],
       [-7.70799496e-01],
       [ 1.73093077e+00],
       [ 1.48804434e+00],
       [-2.25654390e-01],
       [-8.59103751e-01],
       [ 5.50143776e-02],
       [ 1.19784093e-01],
       [-1.71679627e-01],
       [-1.19054233e-01],
       [-7.95088140e-01],
       [-4.14566061e-01],
       [-8.05883092e-01],
       [ 2.64850174e+00],
       [-6.16971422e-01],
       [-2.28353128e-01],
       [-7.24920948e-01],
       [-5.76490350e-01],
       [-1.17839801e-01],
       [ 4.89511220e-01],
       [ 4.96671781e+00],
       [ 7.99866107e-01],
       [-4.69890193e-01],
       [-5.83326247e-02],
       [ 3.27451994e-01],
       [-1.46707394e+00],
       [-4.60444609e-01],
       [ 1.20062872e+00],
       [-2.99869689e-01],
       [-1.39429706e-01],
       [-6.03477731e-01],
       [ 2.87105859e-01],
       [-5.71227810e-01],
       [-7.38414639e-01],
       [-1.02164721e+00],
       [ 2.33131096e-01],
       [ 1.16419576e+00],
       [ 1.08323361e+00],
       [-3.41025446e-01],
       [ 1.17085355e-01],
       [ 6.89217843e-01],
       [-9.51614952e-01],
       [-9.46217476e-01],
       [ 7.24301439e-01],
       [-2.93122844e-01],
       [ 4.49030148e-01],
       [ 8.26853489e-01],
       [ 7.48590082e-01],
       [-3.74084988e-01],
       [ 9.61790396e-01],
       [-1.33897293e-01],
       [-9.94794763e-01],
       [-1.17839801e-01],
       [ 2.33131096e-01],
       [ 7.66042828e-02],
       [ 1.09672730e+00],
       [ 5.76554430e+00],
       [ 2.73612168e-01],
       [ 4.89511220e-01],
       [ 1.04275254e+00],
       [-2.52776708e-01],
       [ 6.91916581e-01],
       [-6.11573945e-01],
       [-2.06493349e-01],
       [ 9.61790396e-01],
       [ 2.71597019e+00],
       [ 3.27586931e-01],
       [-2.79629153e-01],
       [ 8.53840870e-01],
       [-8.19376783e-01],
       [ 4.79669731e+00],
       [-1.04876953e+00],
       [-1.11893672e+00],
       [ 5.23156395e-02],
       [-8.46364165e-01],
       [-5.49502968e-01],
       [-3.60591297e-01],
       [ 5.00989762e+00],
       [-8.86845237e-01],
       [-5.22515587e-01],
       [-5.22515587e-01],
       [-3.33603916e-01],
       [ 2.87105859e-01],
       [-9.94794763e-01],
       [-3.33603916e-01],
       [-3.47097607e-01],
       [-9.00473864e-01],
       [-5.89984040e-01],
       [-5.76490350e-01],
       [-7.15475364e-01],
       [ 4.57509852e+00],
       [ 5.29690033e-01],
       [ 2.06143714e-01],
       [-4.28059751e-01],
       [-7.52043266e-01],
       [-4.73938300e-01],
       [ 3.68068003e-01],
       [ 2.12890559e-01],
       [ 8.45744656e-01],
       [ 5.83967055e-01],
       [ 3.64605529e-02],
       [-2.39148081e-01],
       [ 7.18903963e-01],
       [-2.80978522e-01],
       [ 1.65662642e-01],
       [-2.53991141e-01],
       [ 2.19637405e-01],
       [-5.76490350e-01],
       [ 6.78422890e-01],
       [ 8.70192525e-01],
       [-9.94794763e-01],
       [-5.62996659e-01],
       [-3.60726234e-01],
       [-2.63873920e-01],
       [ 6.58093302e-02],
       [ 1.65662642e-01],
       [-1.17704864e-01],
       [-6.03477731e-01],
       [ 1.71743708e+00],
       [-7.39764008e-01],
       [ 7.92360916e-01],
       [-1.54284011e-01],
       [-6.16971422e-01],
       [ 3.88219487e-02],
       [-2.85026629e-01],
       [ 7.43192606e-01],
       [ 8.80828252e-01],
       [ 1.72320435e-02],
       [ 1.92650023e-01],
       [-6.06176469e-01],
       [ 5.42820203e+00],
       [-3.88928048e-01],
       [ 8.47004973e-02],
       [-1.46707394e+00],
       [-8.66693752e-02],
       [-3.20110225e-01],
       [ 2.54055221e+00],
       [-1.37945400e-01],
       [-2.32490287e-02],
       [-6.98068503e-01],
       [-5.36009277e-01],
       [ 1.30864341e-01],
       [ 2.04128566e+00],
       [-5.62996659e-01],
       [-2.52641771e-01],
       [-6.11573945e-01],
       [ 4.76017529e-01],
       [-4.55047133e-01],
       [-1.31198555e-01],
       [-9.94794763e-01],
       [-6.97933566e-01],
       [-2.20256914e-01],
       [-1.44692245e-01],
       [ 3.16791978e-01],
       [-4.68540824e-01],

In [ ]:
regressor.score(x_test, y_test)

0.539858460064662